/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_face_Face */

#ifndef _Included_com_jni_face_Face
#define _Included_com_jni_face_Face
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_face_Face
 * Method:    sdkInit
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_face_Face_sdkInit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jni_face_Face
 * Method:    sdkDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jni_face_Face_sdkDestroy
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_face_Face
 * Method:    isAuth
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_jni_face_Face_isAuth
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_face_Face
 * Method:    detect
 * Signature: (JI)[Lcom/jni/struct/FaceBox;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jni_face_Face_detect
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_jni_face_Face
 * Method:    track
 * Signature: (JI)[Lcom/jni/struct/TrackFaceInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jni_face_Face_track
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_jni_face_Face
 * Method:    clearTrackHistory
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_face_Face_clearTrackHistory
  (JNIEnv *, jclass);

/*
 * Class:     com_jni_face_Face
 * Method:    faceAttr
 * Signature: (J)[Lcom/jni/struct/Attribute;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jni_face_Face_faceAttr
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jni_face_Face
 * Method:    faceEyeClose
 * Signature: (J)[Lcom/jni/struct/EyeClose;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jni_face_Face_faceEyeClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jni_face_Face
 * Method:    faceGaze
 * Signature: (J)[Lcom/jni/struct/GazeInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jni_face_Face_faceGaze
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jni_face_Face
 * Method:    faceHeadPose
 * Signature: (J)[Lcom/jni/struct/HeadPose;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jni_face_Face_faceHeadPose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jni_face_Face
 * Method:    faceIllumination
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_jni_face_Face_faceIllumination
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jni_face_Face
 * Method:    faceBlur
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_jni_face_Face_faceBlur
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jni_face_Face
 * Method:    faceMouthClose
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_jni_face_Face_faceMouthClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jni_face_Face
 * Method:    faceMouthMask
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_jni_face_Face_faceMouthMask
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jni_face_Face
 * Method:    faceOcclusion
 * Signature: (J)[Lcom/jni/struct/Occlusion;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jni_face_Face_faceOcclusion
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jni_face_Face
 * Method:    darkEnhance
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_jni_face_Face_darkEnhance
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jni_face_Face
 * Method:    faceCrop
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_jni_face_Face_faceCrop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jni_face_Face
 * Method:    faceBest
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_jni_face_Face_faceBest
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jni_face_Face
 * Method:    faceLandmark
 * Signature: (JI)[Lcom/jni/struct/Landmarks;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jni_face_Face_faceLandmark
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_jni_face_Face
 * Method:    faceActionLive
 * Signature: (JI[I)[Lcom/jni/struct/FaceBox;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jni_face_Face_faceActionLive
  (JNIEnv *, jclass, jlong, jint, jintArray);

/*
 * Class:     com_jni_face_Face
 * Method:    clearActionLiveHistory
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_face_Face_clearActionLiveHistory
  (JNIEnv *, jclass);

/*
 * Class:     com_jni_face_Face
 * Method:    faceFeature
 * Signature: (JI)[Lcom/jni/struct/FeatureInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jni_face_Face_faceFeature
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_jni_face_Face
 * Method:    rgbdFeature
 * Signature: (J[BI)[Lcom/jni/struct/FeatureInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jni_face_Face_rgbdFeature
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     com_jni_face_Face
 * Method:    livenessFeature
 * Signature: (JI)[Lcom/jni/struct/LiveFeatureInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jni_face_Face_livenessFeature
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_jni_face_Face
 * Method:    compareFeature
 * Signature: (Lcom/jni/struct/Feature;Lcom/jni/struct/Feature;I)F
 */
JNIEXPORT jfloat JNICALL Java_com_jni_face_Face_compareFeature
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     com_jni_face_Face
 * Method:    rgbLiveness
 * Signature: (J)[Lcom/jni/struct/LivenessInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jni_face_Face_rgbLiveness
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jni_face_Face
 * Method:    nirLiveness
 * Signature: (J)[Lcom/jni/struct/LivenessInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jni_face_Face_nirLiveness
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jni_face_Face
 * Method:    rgbAndDepthLiveness
 * Signature: (JJ)[Lcom/jni/struct/RgbDepthInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jni_face_Face_rgbAndDepthLiveness
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_jni_face_Face
 * Method:    userAdd
 * Signature: (Lcom/jni/struct/Feature;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_face_Face_userAdd
  (JNIEnv *, jclass, jobject, jstring, jstring, jstring);

/*
 * Class:     com_jni_face_Face
 * Method:    userUpdate
 * Signature: (Lcom/jni/struct/Feature;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_face_Face_userUpdate
  (JNIEnv *, jclass, jobject, jstring, jstring, jstring);

/*
 * Class:     com_jni_face_Face
 * Method:    userFaceDelete
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_face_Face_userFaceDelete
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_jni_face_Face
 * Method:    userDelete
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_face_Face_userDelete
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_jni_face_Face
 * Method:    groupAdd
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_face_Face_groupAdd
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_jni_face_Face
 * Method:    groupDelete
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_face_Face_groupDelete
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_jni_face_Face
 * Method:    getUserInfo
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_face_Face_getUserInfo
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_jni_face_Face
 * Method:    getUserList
 * Signature: (Ljava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_face_Face_getUserList
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_jni_face_Face
 * Method:    getGroupList
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_face_Face_getGroupList
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_jni_face_Face
 * Method:    identify
 * Signature: (Lcom/jni/struct/Feature;Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_face_Face_identify
  (JNIEnv *, jclass, jobject, jstring, jstring, jint);

/*
 * Class:     com_jni_face_Face
 * Method:    identifyWithAll
 * Signature: (Lcom/jni/struct/Feature;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_face_Face_identifyWithAll
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_jni_face_Face
 * Method:    loadDbFace
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_jni_face_Face_loadDbFace
  (JNIEnv *, jclass);

/*
 * Class:     com_jni_face_Face
 * Method:    openOrbe
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_face_Face_openOrbe
  (JNIEnv *, jclass);

/*
 * Class:     com_jni_face_Face
 * Method:    cameraOrbe
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_jni_face_Face_cameraOrbe
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_jni_face_Face
 * Method:    closeOrbe
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_face_Face_closeOrbe
  (JNIEnv *, jclass);

/*
 * Class:     com_jni_face_Face
 * Method:    openHjimi
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_face_Face_openHjimi
  (JNIEnv *, jclass);

/*
 * Class:     com_jni_face_Face
 * Method:    cameraHjimi
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_jni_face_Face_cameraHjimi
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_jni_face_Face
 * Method:    closeHjimi
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_face_Face_closeHjimi
  (JNIEnv *, jclass);

/*
 * Class:     com_jni_face_Face
 * Method:    loadRgbDetectAbility
 * Signature: (Lcom/jni/struct/DetectConf;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_face_Face_loadRgbDetectAbility
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_jni_face_Face
 * Method:    loadNirDetectAbility
 * Signature: (Lcom/jni/struct/DetectConf;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_face_Face_loadNirDetectAbility
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_jni_face_Face
 * Method:    loadFastAlignAbility
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_com_jni_face_Face_loadFastAlignAbility
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     com_jni_face_Face
 * Method:    loadAccurateAlignAbility
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_com_jni_face_Face_loadAccurateAlignAbility
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     com_jni_face_Face
 * Method:    loadNirAlignAbility
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_com_jni_face_Face_loadNirAlignAbility
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     com_jni_face_Face
 * Method:    loadRgbTrackAbility
 * Signature: (Lcom/jni/struct/TrackConf;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_face_Face_loadRgbTrackAbility
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_jni_face_Face
 * Method:    loadNirTrackAbility
 * Signature: (Lcom/jni/struct/TrackConf;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_face_Face_loadNirTrackAbility
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_jni_face_Face
 * Method:    loadCropFaceAbility
 * Signature: (Lcom/jni/struct/CropFaceConf;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_face_Face_loadCropFaceAbility
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_jni_face_Face
 * Method:    loadOtherAbility
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_face_Face_loadOtherAbility
  (JNIEnv *, jclass);

/*
 * Class:     com_jni_face_Face
 * Method:    loadActionLiveAbility
 * Signature: (Lcom/jni/struct/ActionLiveConf;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_face_Face_loadActionLiveAbility
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
